theiabackup_homepage:
    path:     /
    defaults: { _controller: WeCodePixelsTheiaBackupBundle:Dashboard:index }

theiabackup_ajax_backup_status:
    path:     /ajax/status/{backupId}
    defaults: { _controller: WeCodePixelsTheiaBackupBundle:BackupStatus:index }
