services:
    wecodepixels.theia_backup.configuration_service:
        class: WeCodePixels\TheiaBackupBundle\ConfigurationService
        arguments: []
#    asd.example:
#        class: AsdBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
