services:
    wecodepixels.theia_backup.configuration_service:
        class: WeCodePixels\TheiaBackupBundle\ConfigurationService
        arguments: []
    wecodepixels.theia_backup.backup_status_service:
        class: WeCodePixels\TheiaBackupBundle\BackupStatusService
        arguments:
            configuration_service: '@wecodepixels.theia_backup.configuration_service'
            entity_manager: '@doctrine.orm.default_entity_manager'
